import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Button from "../components/atoms/Button";
import style from "../styles/Home.module.css";
import Form from "react-bootstrap/Form";

const Home: NextPage = () => {
    const BASE_URL = "htpndbkj";

    const [data, setData] = React.useState(2);
    const [isActive, setIsActive] = React.useState(null);

    const [isAdmin, setIsAdmin] = React.useState(true);

    const globalState = {};

    const globalReducer = {};

    const onSubmit = () => {};

    const onUpdate = () => {};

    const onChangeDesa = () => {};

    // UseEffect, useState
    // React.useEffect(() => {

    // });

    const decrement = () => {
        setData(data + 1);
    };

    const chooseNumber = async (value: any) => {
        console.log(value);
    };

    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <p>{data}</p>

                {isAdmin && (
                    <Button onClick={() => setData(data + 1)} text="Plus" />
                )}

                <Button onClick={() => setData(data - 1)} text="Minus" />
            </div>
            <div></div>
        </>
    );
};

export default Home;
